openapi: 3.0.3
info:
  title: OpenAPI Demo
  description: Simple Demo to show integraton of OpenAPI into SpringBoot.
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080

tags:
  - name: "demo"
    description: "Simple demo operations"
paths:
  /hello:
    get:
      tags:
        - demo
      summary: 'Show simple greeting'
      operationId: hello
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: "Hello World"
  /hello/{name}:
    get:
      tags:
        - demo
      summary: 'Shows greeting with text as parameter'
      operationId: helloName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: "Hello ${name}"