openapi: 3.0.3
info:
  title: OpenAPI Demo
  description: Simple Demo to show integraton of OpenAPI into SpringBoot.
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080

tags:
  - name: "demo"
    description: "Simple demo operations"
paths:
  /hello:
    get:
      tags:
        - demo
      summary: 'Show simple greeting'
      operationId: hello
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: "Hello World"
    post:
      tags:
        - demo
      summary: "shows greeting to person"
      operationId: helloPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/person'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/greeting'

  /hello/{name}:
    get:
      tags:
        - demo
      summary: 'Shows greeting with text as parameter'
      operationId: helloName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: "Hello ${name}"
components:
  schemas:
    person:
      type: object
      properties:
        title:
          type: string
        firstname:
          type: string
        lastname:
          type: string
    greeting:
      type: object
      properties:
        text:
          type: string